// Diccionario Oficial de Aves de Sabinas Hidalgo
// Mapeo: "nombre cientifico en minusculas" : "Nombre Común en Español"
export const diccionarioAves = {
    "crypturellus cinnamomeus": "Tinamú Canelo",
    "dendrocygna autumnalis": "Pijije Alas Blancas",
    "cairina moschata": "Pato Real",
    "spatula discors": "Cerceta Alas Azules",
    "spatula clypeata": "Pato Cucharón Norteño",
    "anas acuta": "Pato Golondrino",
    "ortalis vetula": "Chachalaca Oriental",
    "colinus virginianus": "Codorniz Cotuí",
    "callipepla squamata": "Codorniz Escamoza",
    "meleagris gallopavo": "Guajolote Norteño",
    "podilymbus podiceps": "Zambullidor Pico Grueso",
    "columba livia": "Paloma Doméstica",
    "patagioenas fasciata": "Paloma Encinera",
    "columbina inca": "Tortolita Cola Larga",
    "columbina passerina": "Tortolita Pico Rojo",
    "leptotila verreauxi": "Paloma Arroyera",
    "zenaida asiatica": "Paloma Alas Blancas",
    "zenaida macroura": "Huilota Común",
    "geococcyx californianus": "Correcaminos Norteño",
    "crotophaga sulcirostris": "Garrapatero Pijuy",
    "nyctidromus albicollis": "Chotacabras Pauraque",
    "antrostomus arizonae": "Tapacamino Cuerporruín Mexicano",
    "aeronautes saxatalis": "Vencejo Pecho Blanco",
    "eugenes fulgens": "Colibrí Magnífico",
    "lampornis clemenciae": "Colibrí Garganta Azul",
    "archilochus colubris": "Colibrí Garganta Rubí",
    "cynanthus latirostris": "Colibrí Pico Ancho",
    "amazilia yucatanensis": "Colibrí Vientre Canela",
    "fulica americana": "Gallareta Americana",
    "charadrius vociferus": "Chorlo Tildío",
    "actitis macularius": "Playero Alzacolita",
    "nannopterum brasilianum": "Cormorán Neotropical",
    "pelecanus erythrorhynchos": "Pelícano Blanco Americano",
    "ardea herodias": "Garza Morena",
    "ardea alba": "Garza Blanca",
    "egretta thula": "Garza Dedos Dorados",
    "bubulcus ibis": "Garza Ganadera",
    "butorides virescens": "Garcita Verde",
    "nycticorax nycticorax": "Garza Nocturna Corona Negra",
    "nyctanassa violacea": "Garza Nocturna Corona Clara",
    "plegadis chihi": "Ibis Ojos Rojos",
    "coragyps atratus": "Zopilote Común",
    "cathartes aura": "Zopilote Aura",
    "pandion haliaetus": "Águila Pescadora",
    "chondrohierax uncinatus": "Gavilán Pico Gancho",
    "elanus leucurus": "Milano Cola Blanca",
    "aquila chrysaetos": "Águila Real",
    "circus hudsonius": "Gavilán Rastrero",
    "accipiter striatus": "Gavilán Pecho Canela",
    "accipiter cooperii": "Gavilán de Cooper",
    "buteogallus anthracinus": "Aguililla Negra Menor",
    "parabuteo unicinctus": "Aguililla Rojinegra",
    "buteo lineatus": "Aguililla Pecho Rojo",
    "buteo plagiatus": "Aguililla Gris",
    "buteo albonotatus": "Aguililla Aura",
    "buteo jamaicensis": "Aguililla Cola Roja",
    "tyto alba": "Lechuza de Campanario",
    "megascops asio": "Tecolote del Este",
    "bubo virginianus": "Búho Cornudo",
    "glaucidium gnoma": "Tecolote Serrano",
    "glaucidium brasilianum": "Tecolote Bajeño",
    "trogon elegans": "Coa Elegante",
    "momotus coeruliceps": "Momoto Corona Azul",
    "megaceryle torquata": "Martín Pescador de Collar",
    "megaceryle alcyon": "Martín Pescador Norteño",
    "chloroceryle americana": "Martín Pescador Verde",
    "melanerpes formicivorus": "Carpintero Bellotero",
    "melanerpes aurifrons": "Carpintero Cheje",
    "sphyrapicus varius": "Carpintero Moteado",
    "sphyrapicus nuchalis": "Carpintero Nuca Roja",
    "dryobates scalaris": "Carpintero Mexicano",
    "dryobates villosus": "Carpintero Albinegro Mayor",
    "colaptes rubiginosus": "Carpintero Olivio",
    "colaptes auratus": "Carpintero de Pechera Común",
    "micrastur semitorquatus": "Halcón Selvático de Collar",
    "caracara plancus": "Caracara Quebrantahuesos",
    "falco sparverius": "Cernícola Americano",
    "falco columbarius": "Halcón Esmerejón",
    "falco rufigularis": "Halcón Murcielaguero",
    "falco peregrinus": "Halcón Peregrino",
    "psittacara holochlorus": "Perico Mexicano",
    "rhynchopsitta terrisi": "Cotorra Serrana Oriental",
    "amazona viridigenalis": "Loro Tamaulipeco",
    "amazona autumnalis": "Loro Cachetes Amarillos",
    "amazona oratrix": "Loro Cabeza Amarilla (Oratrix)",
    "pachyramphus aglaiae": "Cabezón Degollado",
    "camptostoma imberbe": "Mosquerito Chillón",
    "contopus pertinax": "Papamoscas José María",
    "contopus sordidulus": "Papamoscas del Oeste",
    "empidonax minimus": "Papamoscas Chico",
    "sayornis nigricans": "Papamoscas Negro",
    "sayornis phoebe": "Papamoscas Fibí",
    "sayornis saya": "Papamoscas Llanero",
    "pyrocephalus rubinus": "Papamoscas Cardenalito",
    "myiarchus tuberculifer": "Papamoscas Triste",
    "myiarchus cinerascens": "Papamoscas Cenizo",
    "myiarchus tyrannulus": "Papamoscas Gritón",
    "pitangus sulphuratus": "Luis Bienteveo",
    "myiodynastes luteiventris": "Papamoscas Rayado Común",
    "tyrannus couchii": "Tirano Cuír",
    "tyrannus forficatus": "Tirano Tijereta Rosado",
    "vireo atricapilla": "Vireo Gorra Negra",
    "vireo griseus": "Vireo Ojos Blancos",
    "vireo huttoni": "Vireo Reyezuelo",
    "vireo solitarius": "Vireo Anteojillo",
    "vireo gilvus": "Vireo Gorjeador",
    "vireo flavoviridis": "Vireo Verdeamarillo",
    "psilorhinus morio": "Chara Pea",
    "cyanocorax yncas": "Chara Verde",
    "aphelocoma wollweberi": "Chara Pecho Gris",
    "corvus cryptoleucus": "Cuervo Llanero",
    "corvus corax": "Cuervo Común",
    "lanius ludovicianus": "Verdugo Americano",
    "baeolophus wollweberi": "Carbonero Embridado",
    "baeolophus atricristatus": "Carbonero Cresta Negra",
    "hirundo rustica": "Golondrina Tijereta",
    "petrochelidon pyrrhonota": "Golondrina Risquera",
    "petrochelidon fulva": "Golondrina Pueblera",
    "psaltriparus minimus": "Sastrecillo",
    "corthylio calendula": "Reyezuelo Matraquita",
    "bombycilla cedrorum": "Chinito",
    "certhia americana": "Trepadorcito Americano",
    "polioptila caerulea": "Perlita Azulgris",
    "polioptila melanura": "Perlita del Desierto",
    "catherpes mexicanus": "Saltapared Barranqueño",
    "troglodytes aedon": "Saltapared Común",
    "thryothorus ludovicianus": "Saltapared de Carolina",
    "thryomanes bewickii": "Saltapared Cola Larga",
    "pheugopedius maculipectus": "Saltapared Moteado",
    "dumetella carolinensis": "Maullador Gris",
    "toxostoma curvirostre": "Cuicacoche Pico Curvo",
    "toxostoma longirostre": "Cuicacoche Pico Largo",
    "mimus polyglottos": "Centzontle Norteño",
    "sialia mexicana": "Azulejo Garganta Azul",
    "myadestes occidentalis": "Clarín Jilguero",
    "catharus guttatus": "Zorzal Cola Canela",
    "turdus grayi": "Mirlo Café",
    "turdus migratorius": "Mirlo Primavera",
    "peucedramus taeniatus": "Ocotero Enmascarado",
    "passer domesticus": "Gorrión Doméstico",
    "haemorhous mexicanus": "Pinzón Mexicano",
    "spinus psaltria": "Jilguerito Dominico",
    "arremonops rufivirgatus": "Rascador Oliváceo",
    "atlapetes pileatus": "Rascador Gorra Canela",
    "aimophila ruficeps": "Zacatonero Corona Canela",
    "spizella passerina": "Gorrión Cejas Blancas",
    "spizella wortheni": "Gorrión de Worthen",
    "chondestes grammacus": "Gorrión Arlequín",
    "melospiza lincolnii": "Gorrión de Lincoln",
    "agelaius phoeniceus": "Tordo Sargento",
    "sturnella magna": "Pradero Tortillaconchile",
    "quiscalus mexicanus": "Zanate Mayor",
    "molothrus aeneus": "Tordo Ojos Rojos",
    "molothrus ater": "Tordo Cabeza Café",
    "icterus cucullatus": "Calandria Dorso Negro Menor",
    "icterus graduacauda": "Calandria Capucha Negra",
    "mniotilta varia": "Chipe Trepador",
    "oreothlypis superciliosa": "Chipe Cejas Blancas",
    "leiothlypis celata": "Chipe Oliváceo",
    "leiothlypis ruficapilla": "Chipe Cabeza Gris",
    "setophaga pitiayumi": "Chipe Tropical",
    "setophaga petechia": "Chipe Amarillo",
    "setophaga coronata": "Chipe Rabadilla Amarilla",
    "setophaga townsendi": "Chipe de Townsend",
    "setophaga chrysoparia": "Chipe Cachetes Amarillos",
    "setophaga virens": "Chipe Dorso Verde",
    "basileuterus rufifrons": "Chipe Gorra Canela Común",
    "cardellina pusilla": "Chipe Corona Negra",
    "myioborus pictus": "Pavito Alas Blancas",
    "piranga flava": "Piranga Encinera",
    "rhodothraupis celaeno": "Picogordo Cuello Rojo",
    "cardinalis cardinalis": "Cardenal Rojo",
    "cardinalis sinuatus": "Cardenal Desértico",
    "pheucticus melanocephalus": "Picogordo Tigrillo",
    "passerina caerulea": "Picogordo Azul",
    "passerina cyanea": "Colorín Azul",
    "passerina versicolor": "Colorín Morado",
    "passerina ciris": "Colorín Sietecolores",
    "tiaris olivaceus": "Semillero Oliváceo",
    "streptopelia decaocto": "Tórtola de Collar Turca",
    "falco mexicanus": "Halcón Mexicano",
    "archilochus alexandri": "Colibrí Barba Negra",
    "gallinula galeata": "Gallineta Frente Roja",
    "tyrannus melancholicus": "Tirano Pirirí",
    "tigrisoma mexicanum": "Garza Tigre Mexicana",
    "anas diazi": "Pato Mexicano"
};